// E-commerce-platform-backend/utils/data.js

const products = [
  // --- 10 Men's Products ---
  {
    name: 'Classic Crewneck T-Shirt',
    description: 'A timeless wardrobe staple, made from soft, breathable cotton.',
    price: 25.0,
    category: 'men',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6AACCVr9ljprAfTkynLAM5U3jtNUJnakfkw&s',
    stock: 100,
    isDemanded: true,
  },
  {
    name: 'Slim-Fit Chinos',
    description: 'Versatile and stylish chinos that can be dressed up or down.',
    price: 60.0,
    category: 'men',
    imageUrl: 'https://fabrilife.com/products/657bef5d855de-square.jpg',
    stock: 70,
    isDemanded: true,
  },
  {
    name: 'Quilted Puffer Jacket',
    description: 'Stay warm without the bulk in this stylish quilted puffer jacket.',
    price: 120.0,
    category: 'men',
    imageUrl: 'https://static1.nordic.pictures/51253343-thickbox_default/karl-kani-sport-patch-square-quilted-puffer-jacket-m-60760019-xl.jpg',
    stock: 40,
    isDemanded: true,
  },
  {
    name: 'Leather Ankle Boots',
    description: 'Durable and fashionable leather boots for any occasion.',
    price: 150.0,
    category: 'men',
    imageUrl: 'https://assets.digitalcontent.marksandspencer.app/image/upload/w_600,h_780,q_auto,f_auto,e_sharpen/SD_01_T02_8804_Y0_X_EC_0',
    stock: 30,
    isDemanded: true,
  },
  {
    name: 'Vintage Graphic Tee',
    description: 'A soft tee with a unique, vintage-inspired graphic print.',
    price: 35.0,
    category: 'men',
    imageUrl: 'https://i.etsystatic.com/5245256/r/il/7697cd/2094774451/il_570xN.2094774451_k9mb.jpg',
    stock: 80,
    isDemanded: false,
  },
  {
    name: 'Classic Denim Jacket',
    description: 'A must-have denim jacket that gets better with age.',
    price: 95.0,
    category: 'men',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRspl9yMVCS5Wir_g8yVJuk_AIfww_lZDTNuw&s',
    stock: 50,
    isDemanded: false,
  },
  {
    name: 'Performance Polo Shirt',
    description: 'Moisture-wicking and comfortable, perfect for an active day.',
    price: 45.0,
    category: 'men',
    imageUrl: 'https://trendygolf.com/cdn/shop/files/d9ea00ca-0a03-4d94-8661-eebcd76b3a99_350x.jpg?v=1753096058',
    stock: 65,
    isDemanded: false,
  },
  {
    name: 'Relaxed Fit Jeans',
    description: 'Classic relaxed fit jeans for ultimate comfort and style.',
    price: 70.0,
    category: 'men',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0420/7073/7058/files/a9c1e1a511dbe0d1e0eb47291df74bac_815ff763-8885-48a1-875a-f294a14a0f63.jpg?v=1731386873&quality=20',
    stock: 90,
    isDemanded: false,
  },
  {
    name: 'Classic Canvas Sneakers',
    description: 'Go-to sneakers for a casual, effortless look.',
    price: 55.0,
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1898&auto=format&fit=crop',
    stock: 110,
    isDemanded: false,
  },
  {
    name: 'Fleece-Lined Hoodie',
    description: 'Ultra-soft and warm, this hoodie is perfect for chilly days.',
    price: 65.0,
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1509942774463-acf339cf87d5?q=80&w=1887&auto=format&fit=crop',
    stock: 75,
    isDemanded: false,
  },

  // --- 10 Women's Products (with updated image URLs) ---
  {
    name: 'Floral Wrap Midi Dress',
    description: 'A beautiful and flattering dress with a vibrant floral pattern.',
    price: 85.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS55Pu0Br272m50LZalgI4qhAiBNoCJEjj86A&s',
    stock: 50,
    isDemanded: true,
  },
  {
    name: 'Silk Camisole Top',
    description: 'A luxurious silk top that adds a touch of elegance to any outfit.',
    price: 45.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRviO0poeIWZcyM6_Ja72atPSG0XgT8jc3TiA&s',
    stock: 80,
    isDemanded: true,
  },
  {
    name: 'High-Waisted Skinny Jeans',
    description: 'Comfortable and stylish high-waisted jeans that hug your curves.',
    price: 75.0,
    category: 'women',
    imageUrl: 'https://b-cdn.gutsgusto.com/pictures/full/95437.webp',
    stock: 90,
    isDemanded: true,
  },
  {
    name: 'Classic Trench Coat',
    description: 'A timeless trench coat that is perfect for any season.',
    price: 180.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr_nX5Mm83v_JnUx52qQkUR70bSNp_8v7t5Q&s',
    stock: 25,
    isDemanded: true,
  },
  {
    name: 'Oversized Poplin Blouse',
    description: 'A crisp, oversized blouse for a modern, chic look.',
    price: 65.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYCvHrFI1WPR2jrpXdTs_73Ombotgit9upzw&s',
    stock: 60,
    isDemanded: false,
  },
  {
    name: 'Pleated Crepe Trousers',
    description: 'Elegant trousers with a beautiful drape, perfect for work or evening.',
    price: 90.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmGGRZJAY0LyuMwnWV6toA2pMKNuaW238HmQ&s',
    stock: 45,
    isDemanded: false,
  },
  {
    name: 'Cashmere Turtleneck',
    description: 'Luxuriously soft and warm, an essential for colder months.',
    price: 250.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVhxzKWSPjoY1VjEmwi8_FEYYGJG6NA0UHBw&s',
    stock: 20,
    isDemanded: false,
  },
  {
    name: 'Faux Leather Leggings',
    description: 'Sleek and versatile leggings that add an edge to any outfit.',
    price: 55.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf3s8qclRPF9vUsx8zPT2U_Ak_GBixf9oNaw&s',
    stock: 100,
    isDemanded: false,
  },
  {
    name: 'Suede Ankle Booties',
    description: 'Stylish and comfortable booties to complete any fall look.',
    price: 130.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToZT5wCYe1x8n6WkpYzPfdpdn_006K_PnhYw&s',
    stock: 40,
    isDemanded: false,
  },
  {
    name: 'Leather Crossbody Bag',
    description: 'A chic and practical bag for your everyday essentials.',
    price: 110.0,
    category: 'women',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3rPI_QGed2pB5EE_nhOl3Ey_Zq8mxMe7AZA&s',
    stock: 55,
    isDemanded: false,
  },

  // --- 10 Kids' Products (with updated image URLs) ---
  {
    name: 'Dinosaur Graphic T-Shirt',
    description: 'A fun and comfortable t-shirt for your little dinosaur enthusiast.',
    price: 20.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ44FLmwyLH4Cob-l2R5NV4j5RTWg6Tzyud3Q&s',
    stock: 120,
    isDemanded: true,
  },
  {
    name: 'Embroidered Denim Jacket',
    description: 'A stylish and durable denim jacket with beautiful embroidery.',
    price: 55.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCZu8DdaoQGK5nx0TxQzZj5bhUIpkF-_sphA&s',
    stock: 60,
    isDemanded: true,
  },
  {
    name: 'Pull-On Cargo Shorts',
    description: 'Comfortable and practical shorts for all their adventures.',
    price: 25.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYvEzZYB6pXAj1OEmEvDaUykUcOlOMMIYrDg&s',
    stock: 150,
    isDemanded: false,
  },
    // ... (rest of the products are fine, only the broken ones are replaced)
    {
    name: 'Ruffle-Sleeve Sundress',
    description: 'A sweet and charming dress perfect for sunny days.',
    price: 40.0,
    category: 'kids',
    imageUrl: 'https://m.media-amazon.com/images/I/915HoXZy9wL._UY1100_.jpg',
    stock: 80,
    isDemanded: false,
  },
  {
    name: 'Color-Block Hoodie',
    description: 'A vibrant and cozy hoodie to keep them warm and stylish.',
    price: 45.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXAUwiog2822dF1SujXdldezSF5aYX23Tryw&s',
    stock: 100,
    isDemanded: false,
  },
  {
    name: 'High-Top Sneakers',
    description: 'Cool and comfortable sneakers that are ready for playtime.',
    price: 50.0,
    category: 'kids',
    imageUrl: 'https://baccabucci.com/cdn/shop/products/01_MG_8956_2_231eef1d-2648-4b67-a56e-06987c690d2a.jpg?v=1659946816&width=1800',
    stock: 90,
    isDemanded: false,
  },
  {
    name: 'Cozy Flannel Pajama Set',
    description: 'Soft and warm pajamas for a comfortable night\'s sleep.',
    price: 35.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWioX8TIkiL5UlbLmsd8z84i7BaklZIXVfrQ&s',
    stock: 110,
    isDemanded: false,
  },
  {
    name: 'Sparkle Graphic Leggings',
    description: 'Fun leggings with a touch of sparkle for a playful look.',
    price: 22.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMpQaYF7YtM3hJ8aS1Rk05Ju1iI5WZb5K-WA&s',
    stock: 130,
    isDemanded: false,
  },
  {
    name: 'Waterproof Rain Jacket',
    description: 'Keep them dry on rainy days with this durable jacket.',
    price: 60.0,
    category: 'kids',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1b0tAsAeeJtcs-aSShyUl2tg_T_YfKqpxoQ&s',
    stock: 70,
    isDemanded: false,
  },
  {
    name: 'Kids\' Themed Backpack',
    description: 'A fun and spacious backpack for school and adventures.',
    price: 38.0,
    category: 'kids',
    imageUrl: 'https://homafy.com/wp-content/uploads/2024/03/space-theme-bag.jpeg',
    stock: 85,
    isDemanded: true,
  },

  // --- 10 Beauty Products ---
  {
    name: 'Hydrating Face Serum',
    description: 'A powerful serum that hydrates and revitalizes your skin.',
    price: 40.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWtvNmHSltRxeoJoN78rdcZ4lv47lQJFaGEA&s',
    stock: 90,
    isDemanded: true,
  },
  {
    name: 'Matte Lipstick Set',
    description: 'A set of beautiful, long-lasting matte lipsticks in various shades.',
    price: 50.0,
    category: 'beauty',
    imageUrl: 'https://m.media-amazon.com/images/I/61E1o1M6Y6L._UF1000,1000_QL80_.jpg',
    stock: 75,
    isDemanded: true,
  },
  {
    name: 'Vitamin C Brightening Cream',
    description: 'A daily moisturizer that brightens and evens out skin tone.',
    price: 55.0,
    category: 'beauty',
    imageUrl: 'https://dr.rashel.in/cdn/shop/files/Vitamin_C_Day_Cream.jpg?v=1755965572',
    stock: 80,
    isDemanded: false,
  },
  {
    name: 'Gentle Gel Cleanser',
    description: 'A mild cleanser that effectively removes impurities without stripping skin.',
    price: 28.0,
    category: 'beauty',
    imageUrl: 'https://www.honest.com/dw/image/v2/BDBW_PRD/on/demandware.static/-/Sites-HC-master-catalog/default/dwef80ca87/images/large/Gentle-Gel-Cleanser/Restage_2025/B10RCG00V5FLS_GGCleanser_5oz_XX_Model_JohannaC_1925_PH6_1x1.jpg?sw=1000&sh=1000&sm=fit',
    stock: 120,
    isDemanded: false,
  },
  {
    name: 'Volumizing Mascara',
    description: 'Get thicker, fuller lashes with this long-wearing mascara.',
    price: 24.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2SIGH6l-jw2v6K1pXxpneHORy2l-rDHPlsg&s',
    stock: 150,
    isDemanded: false,
  },
  {
    name: 'Rosewater Facial Mist',
    description: 'A refreshing mist to hydrate and soothe your skin throughout the day.',
    price: 20.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIVLrCjuy68cNMI2w7RTQ9wxaSMp4pmA_f5w&s',
    stock: 100,
    isDemanded: false,
  },
  {
    name: 'Eyeshadow Palette - Nude Tones',
    description: 'A versatile palette with a range of neutral shades for any look.',
    price: 48.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyPWqhwtsdKCVAmS2r_e0cSCfRx6hHNj23PQ&s',
    stock: 65,
    isDemanded: false,
  },
  {
    name: 'Charcoal Detox Mask',
    description: 'A deep-cleansing mask to purify pores and absorb excess oil.',
    price: 35.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2OZdLux0LrOCCQi4z9-sgI85AoNlGxzmzyg&s',
    stock: 70,
    isDemanded: false,
  },
  {
    name: 'Liquid Foundation',
    description: 'A lightweight foundation that provides flawless, buildable coverage.',
    price: 42.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0-5Nfrp4jtevtSH75IHBUbCKU2Uh7lPvknw&s',
    stock: 95,
    isDemanded: false,
  },
  {
    name: 'Nourishing Cuticle Oil',
    description: 'Hydrates and strengthens nails and cuticles for a healthy manicure.',
    price: 18.0,
    category: 'beauty',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6BQ7Fv8bz0DaiWlUO4Hv1Mf6wcupzIYDqrg&s',
    stock: 110,
    isDemanded: false,
  },
];

module.exports = products;